// Tilburg trip data
export default {
    id: 'tilburg',
    name: 'Tilburg',
    subtitle: 'Textielstad met karakter',
    dates: 'Nog te plannen',
    banner: '/assets/banner-tilburg.png',
    mapCenter: [51.5580, 5.0840],
    mapZoom: 14,
    categories: [
        {
            type: 'hotel',
            icon: 'bed-double',
            label: 'Hotels',
            color: '#A68A73',
            places: [
                {
                    name: 'Auberge du Bonheur',
                    description: 'Viersterren boutique hotel in de bosrijke Oude Warande. Kamers met eerbetoon aan Tilburgs textielverleden. Combinatie van natuur en stad.',
                    address: 'Bredaseweg 441, 5036 NA Tilburg',
                    coords: [51.5595, 5.0359],
                    link: 'https://www.bonheurhorecagroep.nl/auberge-du-bonheur',
                    tags: ['boutique', 'bos', 'textielgeschiedenis'],
                    image: 'https://aubergedubonheur.nl/wp-content/uploads/sites/2/2025/08/Auberge-du-Bonheur-LR05-768x512.webp',
                    priceLevel: 3,
                    rating: 4.5,
                    openingHours: 'Ma - Vr: 07:00 - 00:00, Za - Zo: 08:00 - 00:00',
                    reviews: [
                        { text: 'The hotel is very nicely located not far from the center but at the same time in a quiet wooded area. The rooms are modern with all the necessities.', author: 'Annick H.' },
                        { text: 'A very special thanks goes to Loes, who not only proved to be extremely kind and available, but also helped us with heartwarming thoughtfulness!', author: 'Francesca M.' },
                        { text: 'Great hotel, clean rooms, easy check-in, friendly staff. Location is beautiful and calm.', author: 'Viktor J.' },
                    ],
                },
                {
                    name: 'Stadsslaperij B&B',
                    description: 'Persoonlijke B&B gerund door gastheer Michel. Sfeervolle kamers met oog voor detail, heerlijk ontbijt en een terras. Op loopafstand van het centrum.',
                    address: 'Fatimastraat 91, 5021 AM Tilburg',
                    coords: [51.5507, 5.0998],
                    link: 'https://www.destadsslaperij.nl',
                    tags: ['B&B', 'persoonlijk', 'ontbijt'],
                    image: 'https://impro.usercontent.one/appid/oneComWsb/domain/destadsslaperij.nl/media/destadsslaperij.nl/onewebmedia/20201010_112026___serialized1.jpg?etag=%2255ec95-61d835b8%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=1600,720&quality=85',
                    priceLevel: 2,
                    rating: 4.9,
                    openingHours: '24/7 bereikbaar',
                    reviews: [
                        { text: 'This little gem is absolutely lovely. The rooms are beautifully decorated and really well thought of. The breakfast is delicious!', author: 'Sabrina P.' },
                        { text: 'Everything about the bnb was perfect. Breakfast was superb. All the little touches and attention to detail were exemplary.', author: 'Valerie R.' },
                        { text: 'Spacious rooms, very comfortable bedding, healthy breakfast. But the real plus is Michel\'s kindness and level of attention.', author: 'Romain A.' },
                    ],
                },
                {
                    name: 'NineT7',
                    description: 'Intiem gastenverblijf in een sfeervol pand aan de Noordstraat, hartje centrum. Persoonlijke ontvangst door eigenaar Esther, met oog voor detail.',
                    address: 'Noordstraat 97, 5038 EH Tilburg',
                    coords: [51.5581, 5.0807],
                    link: 'https://ninet7.bedsandhotels.com/',
                    tags: ['centrum', 'intiem', 'persoonlijk'],
                    image: 'https://img.bedsandhotels.com/media/pic-ninet7-2.jpg',
                    priceLevel: 2,
                    rating: 5.0,
                    openingHours: 'Check-in op afspraak',
                    isWildcard: true,
                    reviews: [
                        { text: 'The location is fantastic, close to the city center but without the noise. We slept wonderfully in the box spring bed.', author: 'Nancy G.' },
                        { text: 'A super nice place, quiet surroundings and close to the city. Very hospitable. Highly recommended.', author: 'Hans L.' },
                    ],
                },
            ],
        },
        {
            type: 'cocktail',
            icon: 'martini',
            label: 'Cocktailbars',
            color: '#D4A3A3',
            places: [
                {
                    name: 'Goesting',
                    description: 'Gezellige bar aan de Heuvelstraat met een warm interieur, heerlijke borrelplanken en een verborgen tuin op het terras. Perfecte plek voor een zomerse avond.',
                    address: 'Heuvelstraat 139a, 5038 AD Tilburg',
                    coords: [51.5553, 5.0825],
                    link: 'https://www.goestingtilburg.nl/',
                    tags: ['borrel', 'tuin', 'gezellig'],
                    image: 'https://www.goestingtilburg.nl/img/250408_GOESTING_HR_022.jpg',
                    priceLevel: 2,
                    rating: 5.0,
                    openingHours: 'Wo: 16:00 - 00:00, Do: 16:00 - 01:00, Vr - Zo: 14:00 - 01:00',
                    isWildcard: true,
                    reviews: [
                        { text: 'Great place for a drink. Delicious drinks and the snacks are also top notch.', author: 'Tom B.' },
                        { text: 'A lively atmosphere, delicious snacks including delicious cheeses, and friendly staff. Highly recommended!', author: 'Jolien B.' },
                        { text: 'Summer evenings or autumnal afternoons are perfect here. The warm atmosphere is created by both the beautiful interior and the friendly service!', author: 'Kaz D.' },
                    ],
                },
                {
                    name: 'Strøming Rooftopbar',
                    description: 'Rooftopbar met spectaculair uitzicht over de Spoorzone en Tilburg. Bijzondere cocktails in een unieke setting hoog boven de stad.',
                    address: 'Spoorlaan 21D, 5038 CB Tilburg',
                    coords: [51.5599, 5.0889],
                    link: 'https://www.stromingtilburg.nl/',
                    tags: ['rooftop', 'uitzicht', 'Spoorzone'],
                    image: 'https://www.stromingtilburg.nl/wp-content/uploads/2025/06/20250411-Stroming-Tilbrug-Rooftop-LR-19.jpg',
                    priceLevel: 2,
                    rating: 4.4,
                    openingHours: 'Ma - Do: 12:00 - 00:00, Vr - Za: 12:00 - 01:00, Zo: 12:00 - 00:00',
                    reviews: [
                        { text: 'Super cozy inside dining experience with shared meals, also this midnight blossom cocktail is probably the best cocktail I\'ve ever had.', author: 'Tim R.' },
                        { text: 'The place is beautifully decorated. The menu offers a great selection, with cocktails that are genuinely well-crafted.', author: 'Guilherme G.' },
                        { text: 'The food was good, as always. A queer-friendly space, which only adds to its appeal.', author: 'Uljana A.' },
                    ],
                },
                {
                    name: 'NØIR Borrel & Bites',
                    description: 'Sfeervol café met excellente cocktails en borrelplanken. In de zomer een prachtige verborgen tuin. Intiem en warm.',
                    address: 'Nieuwlandstraat 51, 5038 SM Tilburg',
                    coords: [51.5555, 5.0828],
                    link: 'https://www.noir.nl/',
                    tags: ['borrel', 'tuin', 'intiem'],
                    image: 'https://www.noir.nl/upload/items/2000/141/etalage-bar.png',
                    priceLevel: 2,
                    rating: 4.7,
                    openingHours: 'Wo - Za: 14:00 - 00:00, Zo: 14:00 - 22:00',
                    reviews: [
                        { text: 'The best bar in Tilburg. High quality snacks, great cocktails, lovely workers and nice atmosphere.', author: 'Clara M.' },
                        { text: 'Fantastic designed bar, amazing lunch.', author: 'patheesen' },
                        { text: 'Noir Borrel & Bites has become our ultimate hangout spot, a place where every visit feels like a cherished reunion.', author: 'Globe Voyage' },
                    ],
                },
                {
                    name: 'Gin Fizz',
                    description: 'Gezellige cocktailbar gespecialiseerd in premium gin-cocktails. Warme sfeer met intiem interieur en deskundige bartenders.',
                    address: 'Oranjestraat 6, 5038 WD Tilburg',
                    coords: [51.5552, 5.0892],
                    link: 'http://www.gin-fizz.nl/',
                    tags: ['gin', 'premium', 'nachtleven'],
                    image: 'https://www.gin-fizz.nl/wp-content/uploads/2023/02/SfeerfotoGinFizz_Fever-Tree.png',
                    priceLevel: 2,
                    rating: 4.5,
                    openingHours: 'Do: 22:00 - 03:00, Vr - Za: 21:00 - 04:00',
                    reviews: [
                        { text: 'Nice cocktails and music.', author: 'Aimee C.' },
                        { text: 'Really cozy, fun and great Gin cocktails served by a well informed, nice staff.', author: 'Artëm D.' },
                        { text: 'Great relaxing place, nice staff.', author: 'Vic V.' },
                    ],
                },
            ],
        },
        {
            type: 'restaurant',
            icon: 'utensils',
            label: 'Restaurants',
            color: '#D19C5B',
            places: [
                {
                    name: 'Eetbar De Wagon',
                    description: 'Dineren in twee authentieke treincoupés uit 1900 in de hippe Spoorzone. Creatieve menukaart met veel vegetarische opties. Absoluut uniek!',
                    address: 'Burgemeester Brokxlaan 1041, 5041 RP Tilburg',
                    coords: [51.5622, 5.0826],
                    link: 'http://eetbardewagon.com/',
                    tags: ['uniek', 'treincoupé', 'Spoorzone'],
                    image: 'https://eetbardewagoncom.lightningbasecdn.com/wp-content/uploads/2022/09/foto-staand-coupe-Eetbar-de-Wagon-Tilburg.jpg',
                    priceLevel: 2,
                    rating: 4.3,
                    openingHours: 'Di - Do: 12:00 - 23:00, Vr - Za: 12:00 - 00:00, Zo: 12:00 - 21:30',
                    reviews: [
                        { text: 'Two historical train wagons connected together to make a restaurant — clever and fun concept. Service was splendid!', author: 'Simply Irmina' },
                        { text: 'We dined in an old-fashioned train carriage, with very comfortable seats and relaxing music. The food was very good.', author: 'sams spaspo' },
                        { text: 'We enjoyed the Korean Style Kibbeling. The crispy, juicy fish in a spicy Korean sauce was delicious.', author: 'Joey' },
                    ],
                },
                {
                    name: 'Gist',
                    description: 'Een van de beste restaurants van Tilburg. Seizoensgebonden deelgerechten met lokale ingrediënten. Groenten in de hoofdrol. Klein en snel volgeboekt!',
                    address: 'Langestraat 65, 5038 SC Tilburg',
                    coords: [51.5555, 5.0841],
                    link: 'http://www.gisttilburg.nl/',
                    tags: ['fine dining', 'lokaal', 'seizoensgebonden'],
                    image: 'https://gisttilburg.nl/wp-content/uploads/2024/03/Header-GIST-Tilburg-1-scaled.jpg',
                    priceLevel: 3,
                    rating: 4.9,
                    openingHours: 'Ma - Vr: 17:00 - 22:00, Za - Zo: 12:00 - 15:00 & 17:00 - 22:00',
                    reviews: [
                        { text: 'Oh my God! Just are serving the best possible cabbage, maybe the best in the world. The sauce to it was magical.', author: 'Mindaugas x' },
                        { text: 'Great modern cuisine, dishes to share, amazing quality yet not too fancy. Best in class chicken or North Sea fish.', author: 'Roan v.d.K.' },
                        { text: 'It was truly the best decision to choose GIST for my PhD defense dinner! All of my guests thoroughly enjoyed the delicious food.', author: 'Zihao L.' },
                    ],
                },
                {
                    name: 'Sarban',
                    description: 'Afghaans restaurant, een begrip in Tilburg. Probeer de Afghaanse proeverij voor een compleet smaakavontuur. Op loopafstand van het station.',
                    address: 'Besterdring 2, 5014 HL Tilburg',
                    coords: [51.5671, 5.0887],
                    link: 'http://www.sarban.nl/',
                    tags: ['Afghaans', 'proeverij', 'populair'],
                    image: 'https://sarban.nl/wp-content/uploads/2019/09/mantoe.jpg',
                    priceLevel: 2,
                    rating: 4.8,
                    openingHours: 'Di - Zo: 17:00 - 22:00',
                    reviews: [
                        { text: 'A truly cozy, family-run spot. The food was excellent — from tender lamb and flavorful veal to the delicious stuffed meat dumplings.', author: 'Rolitta S.' },
                        { text: 'Everything tastes homemade but also very professional! A great experience enjoying delicious Afghan dishes.', author: 'Shima' },
                        { text: 'We opted for the chef\'s recommended menu. We were not disappointed! The food was well presented and flavoursome.', author: 'Patty v.H.' },
                    ],
                },
                {
                    name: 'Nomadas',
                    description: 'Verborgen parel in een woonwijk. Chefs combineren invloeden van Lanzarote, Ecuador en Madrid. Intiem tasting menu met verrassende smaken.',
                    address: 'Academielaan 73, 5037 EV Tilburg',
                    coords: [51.5577, 5.0557],
                    link: 'https://nomadas-gastrobar.nl/',
                    tags: ['tasting menu', 'verborgen', 'internationaal'],
                    image: 'https://nomadas-gastrobar.nl/wp-content/uploads/2024/01/Nomadas-Tafels-op-een-rij.jpg',
                    priceLevel: 3,
                    rating: 4.8,
                    openingHours: 'Wo - Vr: 17:30 - 23:30, Za - Zo: 17:30 - 00:00',
                    reviews: [
                        { text: 'Everything was delicious and presented with such creative care! The atmosphere is incredible, as if you were on vacation!', author: 'Minerva I.' },
                        { text: 'Highly recommended. It was a feast on my tongue. The portion and the price are very reasonable.', author: 'Skye Y.' },
                        { text: 'The Tamarindo Old Fashion was liquid candy. Finally a restaurant that spices their food well!', author: 'jennifer s.' },
                    ],
                },
            ],
        },
        {
            type: 'culture',
            icon: 'ticket',
            label: 'Cultuur',
            color: '#8BAA99',
            places: [
                {
                    name: 'Cinecitta',
                    description: 'Filmtheater met arthouse films, bijzondere vertoningen en een gezellige bar. De filmervaring die je zoekt, geen standaard bioscoop.',
                    address: 'Willem II Straat 29, 5038 BA Tilburg',
                    coords: [51.5584, 5.0862],
                    link: 'http://www.cinecitta.nl/',
                    tags: ['arthouse', 'filmtheater', 'bar'],
                    image: 'https://cinecittatilburg.nl/wp-content/uploads/2022/08/20201130_Cinecitta2_Fotografie-Jules-van-Iperen_026-2.jpg',
                    priceLevel: 2,
                    rating: 4.5,
                    openingHours: 'Dagelijks: 10:00 - 22:30',
                    reviews: [
                        { text: 'The perfect place to relax and enjoy a nice meal and movie. The restaurant is in a beautiful room with high ceilings and art.', author: 'Ian M.' },
                        { text: 'An amazing gem in the heart of Tilburg! Very clean, very comfortable chairs, nice selection of international movies.', author: 'Lora B.' },
                        { text: 'Best personal and service. I personally highly recommend.', author: 'Jose Luis L.' },
                    ],
                },
                {
                    name: 'De NWE Vorst',
                    description: 'Theater in een prachtige oude villa midden in het centrum. Platform voor nieuw talent en verrassende voorstellingen.',
                    address: 'Willem II Straat 49, 5038 BD Tilburg',
                    coords: [51.5570, 5.0864],
                    link: 'http://www.denieuwevorst.nl/',
                    tags: ['theater', 'villa', 'nieuw talent'],
                    image: 'https://denieuwevorst.ams3.cdn.digitaloceanspaces.com/main/_resized/algemeen/_1200x630_crop_center-center_82_none/sfeerbeeld-1.jpg',
                    priceLevel: 1,
                    rating: 4.5,
                    openingHours: 'Varieert per voorstelling',
                    reviews: [
                        { text: 'A very cozy setting and an authentic hall, normal prices and a beautiful garden.', author: 'Orange Camp' },
                        { text: 'I saw a great performance here. The theatre is in a beautiful building where you can have a drink and a bite. Great garden too.', author: 'Wanda d.H.' },
                        { text: 'Great home made food at one of the most special spots of the city! Warm welcoming ambience.', author: 'Eleni P.' },
                    ],
                },
                {
                    name: 'Schouwburg Concertzaal Tilburg',
                    description: 'De Schouwburg en Concertzaal in één. Breed programma: cabaret, dans, klassiek, musicals. Meer dan 300 voorstellingen per seizoen.',
                    address: 'Kloosterstraat 1, 5038 VN Tilburg',
                    coords: [51.5541, 5.0848],
                    link: 'https://www.schouwburgconcertzaaltilburg.nl/',
                    tags: ['schouwburg', 'concertzaal', 'breed programma'],
                    image: 'https://static.schouwburgconcertzaaltilburg.nl/cache/je-bezoek.2709/je-bezoek-s1920x1080.jpg',
                    priceLevel: 2,
                    rating: 4.6,
                    openingHours: 'Varieert per voorstelling',
                    reviews: [
                        { text: 'Tony Ann on piano. Great. Wonderful concert and nice bar with view.', author: 'Rob J.' },
                        { text: 'I loved the place and the atmosphere. The great hospitality they offered during the show break was outstanding.', author: 'ahmed k.' },
                        { text: 'Great concert and nice bar with view.', author: 'Alex D.' },
                    ],
                },
                {
                    name: 'Poppodium 013',
                    description: 'Legendarisch poppodium voor live muziek en dancenights. Een van de beste poppodia van Nederland. Geweldige akoestiek en sfeer.',
                    address: 'Veemarktstraat 44, 5017 HS Tilburg',
                    coords: [51.5579, 5.0928],
                    link: 'http://www.013.nl/',
                    tags: ['live muziek', 'poppodium', 'dans'],
                    priceLevel: 2,
                    rating: 4.6,
                    openingHours: 'Kassa: Ma - Vr 13:00 - 17:00, avondprogramma varieert',
                    reviews: [
                        { text: 'The sound quality was excellent, and the view was amazing from every spot in the venue. Very reasonably priced!', author: 'dots' },
                        { text: 'Great stage, not too big but still enough for a nice crowd. Excellent location and great bands.', author: 'Rob v.P.' },
                        { text: 'Great acoustics — not too big but not too small. Love the stadium-style risers in the back, perfect for shorter people.', author: 'mersaydees m.' },
                    ],
                },
            ],
        },
    ],
};
