// Tilburg trip data
export default {
    id: 'tilburg',
    name: 'Tilburg',
    subtitle: 'Textielstad met karakter',
    dates: 'Nog te plannen',
    banner: '/assets/banner-tilburg.png',
    mapCenter: [51.5600, 5.0840],
    mapZoom: 14,
    categories: [
        {
            type: 'hotel',
            icon: 'bed-double',
            label: 'Hotels',
            color: '#A68A73',
            places: [
                {
                    name: 'Hotel Central Tilburg',
                    description: 'Boutique hotel in Art Deco pand uit 1932. Elke kamer is uniek ingericht, geïnspireerd op De Stijl of Dadaïsme. Prachtige glas-in-lood ramen en marmeren trap.',
                    address: 'Spoorlaan 422, 5038 CH Tilburg',
                    coords: [51.5595, 5.0820],
                    link: 'https://hotelcentraltilburg.nl',
                    tags: ['art deco', 'De Stijl', 'centrum'],
                    image: 'https://static.wixstatic.com/media/15b4e3_15b344933f1e4fdebf296f45143fecca~mv2.jpeg/v1/fill/w_800,h_500,q_90/15b4e3_15b344933f1e4fdebf296f45143fecca~mv2.jpeg',
                },
                {
                    name: 'Auberge du Bonheur',
                    description: 'Viersterren boutique hotel in de bosrijke Oude Warande. Kamers met eerbetoon aan Tilburgs textielverleden. Combinatie van natuur en stad.',
                    address: 'Bredaseweg 441, 5036 NA Tilburg',
                    coords: [51.5517, 5.0647],
                    link: 'https://aubergedubonheur.nl',
                    tags: ['boutique', 'bos', 'textielgeschiedenis'],
                    image: 'https://aubergedubonheur.nl/wp-content/uploads/sites/2/2025/08/Auberge-du-Bonheur-LR05-768x512.webp',
                },
                {
                    name: 'Mercure Hotel Tilburg Centrum',
                    description: 'Luxe viersterrenhotel in het hart van de stad, direct aan de Heuvel. Moderne kamers en faciliteiten inclusief Citysauna en een eigen zwembad.',
                    address: 'Heuvel 37, 5038 CP Tilburg',
                    coords: [51.5562, 5.0881],
                    link: 'https://mercure-tilburg.nl',
                    tags: ['centrum', 'hotel', 'luxe'],
                    image: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&q=80&w=800&h=500', // TODO: vervang door eigen foto
                },
            ],
        },
        {
            type: 'cocktail',
            icon: 'martini',
            label: 'Cocktailbars',
            color: '#D4A3A3',
            places: [
                {
                    name: 'Studio',
                    description: 'Stijlvolle cocktailbar aan de Korte Heuvel. Uitgebreide kaart met creatieve cocktails. Geeft ook cocktailworkshops!',
                    address: 'Korte Heuvel 7, 5011 DV Tilburg',
                    coords: [51.5574, 5.0880],
                    link: 'https://studio-tilburg.com',
                    tags: ['cocktails', 'workshops', 'centrum'],
                    image: 'https://studio-tilburg.com/wp-content/uploads/2023/11/DSC9077.png',
                },
                {
                    name: 'Strøming Rooftopbar',
                    description: 'Rooftopbar met spectaculair uitzicht over de Spoorzone en Tilburg. Bijzondere cocktails in een unieke setting hoog boven de stad.',
                    address: 'Spoorzone, Tilburg',
                    coords: [51.5620, 5.0761],
                    link: 'https://stromingtilburg.nl',
                    tags: ['rooftop', 'uitzicht', 'Spoorzone'],
                    image: 'https://www.stromingtilburg.nl/wp-content/uploads/2025/06/20250411-Stroming-Tilbrug-Rooftop-LR-19.jpg',
                },
                {
                    name: 'Noir',
                    description: 'Frans georiënteerd café met excellente cocktails. In de zomer een prachtige verborgen tuin. Intiem en sfeervol.',
                    address: 'Willem II-straat 59, 5038 BD Tilburg',
                    coords: [51.5575, 5.0863],
                    link: null,
                    tags: ['Frans', 'tuin', 'intiem'],
                    image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&q=80&w=800&h=500', // TODO: vervang door eigen foto
                },
                {
                    name: 'Gin Fizz',
                    description: 'Gezellige cocktailbar gespecialiseerd in premium gin-cocktails. Warme sfeer en deskundige bartenders.',
                    address: 'Korte Heuvel 3, 5011 DV Tilburg',
                    coords: [51.5573, 5.0877],
                    link: null,
                    tags: ['gin', 'premium', 'gezellig'],
                    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&q=80&w=800&h=500', // TODO: vervang door eigen foto
                },
            ],
        },
        {
            type: 'restaurant',
            icon: 'utensils',
            label: 'Restaurants',
            color: '#D19C5B',
            places: [
                {
                    name: 'Eetbar De Wagon',
                    description: 'Dineren in twee authentieke treincoupés uit 1900 in de hippe Spoorzone. Creatieve menukaart met veel vegetarische opties. Absoluut uniek!',
                    address: 'Burgemeester Brokxlaan 1, 5041 SB Tilburg',
                    coords: [51.5633, 5.0752],
                    link: 'https://eetbardewagon.nl',
                    tags: ['uniek', 'treincoupé', 'Spoorzone'],
                    image: 'https://eetbardewagoncom.lightningbasecdn.com/wp-content/uploads/2022/09/foto-staand-coupe-Eetbar-de-Wagon-Tilburg.jpg',
                },
                {
                    name: 'Gist',
                    description: 'Een van de beste restaurants van Tilburg (Volkskrant: 8,5). Seizoensgebonden deelgerechten met lokale ingrediënten. Groenten in de hoofdrol. Klein en snel volgeboekt!',
                    address: 'Willem II-straat 1, 5038 BA Tilburg',
                    coords: [51.5581, 5.0853],
                    link: 'https://gisttilburg.nl',
                    tags: ['fine dining', 'lokaal', 'seizoensgebonden'],
                    image: 'https://gisttilburg.nl/wp-content/uploads/2024/03/Header-GIST-Tilburg-1-scaled.jpg',
                },
                {
                    name: 'Sarban',
                    description: 'Afghaans restaurant, een begrip in Tilburg. Probeer de Afghaanse proeverij voor een compleet smaakavontuur. Op loopafstand van het station.',
                    address: 'Besterdring 2, 5014 HL Tilburg',
                    coords: [51.5548, 5.0886],
                    link: 'https://sarban.nl',
                    tags: ['Afghaans', 'proeverij', 'populair'],
                    image: 'https://sarban.nl/wp-content/uploads/2019/09/mantoe.jpg',
                },
                {
                    name: 'Nomadas',
                    description: 'Verborgen parel in een woonwijk. Chefs combineren invloeden van Lanzarote, Ecuador en Madrid. Intiem tasting menu met verrassende smaken.',
                    address: 'Gasthuisring 55, 5041 DT Tilburg',
                    coords: [51.5628, 5.0905],
                    link: 'https://nomadas-gastrobar.nl',
                    tags: ['tasting menu', 'verborgen', 'internationaal'],
                    image: 'https://nomadas-gastrobar.nl/wp-content/uploads/2024/01/Nomadas-Tafels-op-een-rij.jpg',
                },
            ],
        },
        {
            type: 'culture',
            icon: 'ticket',
            label: 'Cultuur',
            color: '#8BAA99',
            places: [
                {
                    name: 'Cinecitta',
                    description: 'Filmtheater met arthouse films, bijzondere vertoningen en een gezellige bar. De filmervaring die je zoekt, geen standaard bioscoop.',
                    address: 'Willem II-straat 29, 5038 BA Tilburg',
                    coords: [51.5569, 5.0857],
                    link: 'https://cinecittatilburg.nl',
                    tags: ['arthouse', 'filmtheater', 'bar'],
                    image: 'https://cinecittatilburg.nl/wp-content/uploads/2022/08/20201130_Cinecitta2_Fotografie-Jules-van-Iperen_026-2.jpg',
                },
                {
                    name: 'De NWE Vorst',
                    description: 'Theater in een prachtige oude villa midden in het centrum. Platform voor nieuw talent en verrassende voorstellingen.',
                    address: 'Willem II-straat 49, 5038 BD Tilburg',
                    coords: [51.5573, 5.0860],
                    link: 'https://denwevorst.nl',
                    tags: ['theater', 'villa', 'nieuw talent'],
                    image: 'https://denieuwevorst.ams3.cdn.digitaloceanspaces.com/main/_resized/algemeen/_1200x630_crop_center-center_82_none/sfeerbeeld-1.jpg',
                },
                {
                    name: 'Schouwburg Concertzaal Tilburg',
                    description: 'De Schouwburg en Concertzaal in één (voorheen Theaters Tilburg). Breed programma: cabaret, dans, klassiek, musicals. Meer dan 300 voorstellingen per seizoen.',
                    address: 'Louis Bouwmeesterplein 1, 5038 TN Tilburg',
                    coords: [51.5590, 5.0818],
                    link: 'https://schouwburgconcertzaaltilburg.nl',
                    tags: ['schouwburg', 'concertzaal', 'breed programma'],
                    image: 'https://static.schouwburgconcertzaaltilburg.nl/cache/je-bezoek.2709/je-bezoek-s1920x1080.jpg',
                },
                {
                    name: 'Poppodium 013',
                    description: 'Legendarisch poppodium voor live muziek en dancenights. Een van de beste poppodia van Nederland.',
                    address: 'Veemarktstraat 44, 5038 CV Tilburg',
                    coords: [51.5590, 5.0860],
                    link: 'https://013.nl',
                    tags: ['live muziek', 'poppodium', 'dans'],
                    image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&q=80&w=800&h=500', // TODO: vervang door eigen foto
                },
            ],
        },
    ],
};
