// Tilburg trip data
export default {
    id: 'tilburg',
    name: 'Tilburg',
    subtitle: 'Textielstad met karakter',
    dates: 'Nog te plannen',
    banner: '/assets/banner-tilburg.png',
    mapCenter: [51.5600, 5.0840],
    mapZoom: 14,
    categories: [
        {
            type: 'hotel',
            icon: '🏨',
            label: 'Hotels',
            color: '#7C3AED',
            places: [
                {
                    name: 'Hotel Central Tilburg',
                    description: 'Boutique hotel in Art Deco pand uit 1932. Elke kamer is uniek ingericht, geïnspireerd op De Stijl of Dadaïsme. Prachtige glas-in-lood ramen en marmeren trap.',
                    address: 'Spoorlaan 422, 5038 CH Tilburg',
                    coords: [51.5595, 5.0820],
                    link: 'https://hotelcentraltilburg.nl',
                    tags: ['art deco', 'De Stijl', 'centrum'],
                },
                {
                    name: 'Auberge du Bonheur',
                    description: 'Viersterren boutique hotel in de bosrijke Oude Warande. Kamers met eerbetoon aan Tilburgs textielverleden. Combinatie van natuur en stad.',
                    address: 'Bredaseweg 441, 5036 NA Tilburg',
                    coords: [51.5517, 5.0647],
                    link: 'https://aubergedubonheur.nl',
                    tags: ['boutique', 'bos', 'textielgeschiedenis'],
                },
                {
                    name: 'De Posthoorn',
                    description: 'Historisch monumentaal pand getransformeerd tot stijlvol hotel & venue. Centraal gelegen bij het station.',
                    address: 'Stationsstraat 40, 5038 ED Tilburg',
                    coords: [51.5606, 5.0839],
                    link: 'https://deposthoorntilburg.nl',
                    tags: ['monumentaal', 'centrum', 'station'],
                },
            ],
        },
        {
            type: 'cocktail',
            icon: '🍸',
            label: 'Cocktailbars',
            color: '#EC4899',
            places: [
                {
                    name: 'Studio',
                    description: 'Stijlvolle cocktailbar aan de Korte Heuvel. Uitgebreide kaart met creatieve cocktails. Geeft ook cocktailworkshops!',
                    address: 'Korte Heuvel 7, 5011 DV Tilburg',
                    coords: [51.5574, 5.0880],
                    link: null,
                    tags: ['cocktails', 'workshops', 'centrum'],
                },
                {
                    name: 'Doloris\' Rooftopbar',
                    description: 'Rooftopbar met spectaculair uitzicht over Tilburg. Cocktails met een eigen twist, zoals hun Pornstar Martini met witte chocolade en mandarijn.',
                    address: 'Spoorzone, Tilburg',
                    coords: [51.5620, 5.0761],
                    link: 'https://doloris.nl',
                    tags: ['rooftop', 'uitzicht', 'creatief'],
                },
                {
                    name: 'Noir',
                    description: 'Frans georiënteerd café met excellente cocktails. In de zomer een prachtige verborgen tuin. Intiem en sfeervol.',
                    address: 'Willem II-straat 59, 5038 BD Tilburg',
                    coords: [51.5575, 5.0863],
                    link: null,
                    tags: ['Frans', 'tuin', 'intiem'],
                },
                {
                    name: 'Gin Fizz',
                    description: 'Gezellige cocktailbar gespecialiseerd in premium gin-cocktails. Warme sfeer en deskundige bartenders.',
                    address: 'Korte Heuvel 3, 5011 DV Tilburg',
                    coords: [51.5573, 5.0877],
                    link: null,
                    tags: ['gin', 'premium', 'gezellig'],
                },
            ],
        },
        {
            type: 'restaurant',
            icon: '🍽️',
            label: 'Restaurants',
            color: '#F59E0B',
            places: [
                {
                    name: 'Eetbar De Wagon',
                    description: 'Dineren in twee authentieke treincoupés uit 1900 in de hippe Spoorzone. Creatieve menukaart met veel vegetarische opties. Absoluut uniek!',
                    address: 'Burgemeester Brokxlaan 1, 5041 SB Tilburg',
                    coords: [51.5633, 5.0752],
                    link: 'https://eetbardewagon.nl',
                    tags: ['uniek', 'treincoupé', 'Spoorzone'],
                },
                {
                    name: 'Gist',
                    description: 'Een van de beste restaurants van Tilburg (Volkskrant: 8,5). Seizoensgebonden deelgerechten met lokale ingrediënten. Groenten in de hoofdrol. Klein en snel volgeboekt!',
                    address: 'Willem II-straat 1, 5038 BA Tilburg',
                    coords: [51.5581, 5.0853],
                    link: null,
                    tags: ['fine dining', 'lokaal', 'seizoensgebonden'],
                },
                {
                    name: 'Sarban',
                    description: 'Afghaans restaurant, een begrip in Tilburg sinds 2010. Probeer de Afghaanse proeverij voor een compleet smaakavontuur. Op loopafstand van het station.',
                    address: 'Koestraat 138, 5014 EG Tilburg',
                    coords: [51.5548, 5.0886],
                    link: null,
                    tags: ['Afghaans', 'proeverij', 'populair'],
                },
                {
                    name: 'Nomadas',
                    description: 'Verborgen parel in een woonwijk. Chefs combineren invloeden van Lanzarote, Ecuador en Madrid. Intiem tasting menu met verrassende smaken.',
                    address: 'Gasthuisring 55, 5041 DT Tilburg',
                    coords: [51.5628, 5.0905],
                    link: null,
                    tags: ['tasting menu', 'verborgen', 'internationaal'],
                },
            ],
        },
        {
            type: 'culture',
            icon: '🎬',
            label: 'Cultuur',
            color: '#14B8A6',
            places: [
                {
                    name: 'Cinecitta',
                    description: 'Filmtheater met arthouse films, bijzondere vertoningen en een gezellige bar. De filmervaring die je zoekt, geen standaard bioscoop.',
                    address: 'Willem II-straat 29, 5038 BA Tilburg',
                    coords: [51.5569, 5.0857],
                    link: null,
                    tags: ['arthouse', 'filmtheater', 'bar'],
                },
                {
                    name: 'De NWE Vorst',
                    description: 'Theater in een prachtige oude villa midden in het centrum. Platform voor nieuw talent en verrassende voorstellingen.',
                    address: 'Willem II-straat 49, 5038 BD Tilburg',
                    coords: [51.5573, 5.0860],
                    link: 'https://denwevorst.nl',
                    tags: ['theater', 'villa', 'nieuw talent'],
                },
                {
                    name: 'Theaters Tilburg',
                    description: 'De Schouwburg en Concertzaal in één. Breed programma: cabaret, dans, klassiek, musicals. Meer dan 300 voorstellingen per seizoen.',
                    address: 'Louis Bouwmeesterplein 1, 5038 TN Tilburg',
                    coords: [51.5590, 5.0818],
                    link: 'https://theaterstilburg.nl',
                    tags: ['schouwburg', 'concertzaal', 'breed programma'],
                },
                {
                    name: 'Poppodium 013',
                    description: 'Legendarisch poppodium voor live muziek en dancenights. Een van de beste poppodia van Nederland.',
                    address: 'Veemarktstraat 44, 5038 CV Tilburg',
                    coords: [51.5590, 5.0860],
                    link: 'https://013.nl',
                    tags: ['live muziek', 'poppodium', 'dans'],
                },
            ],
        },
    ],
};
