// Tilburg v2 trip data — test verbeterde hotel-zoekstrategie
export default {
    id: 'tilburg-v2',
    name: 'Tilburg v2',
    subtitle: 'Textielstad met karakter',
    dates: 'Nog te plannen',
    banner: '/assets/banner-tilburg.png',
    mapCenter: [51.5580, 5.0840],
    mapZoom: 14,
    categories: [
        {
            type: 'hotel',
            icon: 'bed-double',
            label: 'Hotels',
            color: '#A68A73',
            places: [
                {
                    name: 'Stella Suites Boutique Hotel',
                    description: 'Luxe boutique hotel in een monumentale Art Nouveau villa in Goirle. Acht unieke suites met eigen karakter. Heerlijk ontbijt op de kamer en gratis parkeren.',
                    address: 'Kloosterstraat 12, 5051 RD Goirle',
                    coords: [51.5197, 5.0668],
                    link: 'https://www.stellasuites.nl/',
                    tags: ['boutique', 'Art Nouveau', 'luxe'],
                    image: 'https://cdn.prod.website-files.com/6401ec9c06e2044c89d52d2c/642ed014874aa7499ef2f851_Voorkant%20hotel.jpg',
                    priceLevel: 3,
                    rating: 4.8,
                    openingHours: '24/7 bereikbaar',
                    reviews: [
                        { text: 'Great rooms, and staff is exceptionally friendly. Also the breakfast was beyond fantastic, so don\'t skip it!', author: 'Boris G.' },
                        { text: 'My partner, our two kids, and I just returned from a delightful stay at this beautiful boutique hotel. We\'ve never been treated with such exceptional care and attention to detail.', author: 'Daz A.' },
                        { text: 'We were surprised by how pretty the hotel was. It is stylishly decorated with Art Nouveau remnants seen throughout the property. The staff were very friendly and attentive.', author: 'Ralph d.P.' },
                    ],
                },
                {
                    name: 'Auberge du Bonheur',
                    description: 'Viersterren boutique hotel in de bosrijke Oude Warande. Kamers met eerbetoon aan Tilburgs textielverleden. Combinatie van natuur en stad.',
                    address: 'Bredaseweg 441, 5036 NA Tilburg',
                    coords: [51.5595, 5.0359],
                    link: 'https://www.bonheurhorecagroep.nl/auberge-du-bonheur',
                    tags: ['boutique', 'bos', 'textielgeschiedenis'],
                    image: 'https://aubergedubonheur.nl/wp-content/uploads/sites/2/2025/08/Auberge-du-Bonheur-LR05-768x512.webp',
                    priceLevel: 3,
                    rating: 4.5,
                    openingHours: 'Ma - Vr: 07:00 - 00:00, Za - Zo: 08:00 - 00:00',
                    reviews: [
                        { text: 'The hotel is very nicely located not far from the center but at the same time in a quiet wooded area. The rooms are modern with all the necessities.', author: 'Annick H.' },
                        { text: 'A very special thanks goes to Loes, who not only proved to be extremely kind and available, but also helped us with heartwarming thoughtfulness!', author: 'Francesca M.' },
                        { text: 'Great hotel, clean rooms, easy check-in, friendly staff. Location is beautiful and calm.', author: 'Viktor J.' },
                    ],
                },
                {
                    name: '\'t Lanciershuys',
                    description: 'Unieke B&B in een historisch pand uit 1913, op een steenworp van de Piushaven en het centrum. Gastheer Henk serveert een fantastisch ontbijt met huisgemaakte jam.',
                    address: 'Lanciersstraat 11, 5017 CR Tilburg',
                    coords: [51.5553, 5.0964],
                    link: 'https://t-lanciershuys.com/',
                    tags: ['B&B', 'historisch', 'Piushaven'],
                    image: 'https://www.t-lanciershuys.com/_assets/media/0f1a2f82f8f1fd1302e7de261c44dd24.jpg',
                    priceLevel: 2,
                    rating: 4.8,
                    openingHours: 'Check-in op afspraak',
                    reviews: [
                        { text: 'The perfect location, a 10+ minute walk to the city center and 013. The host was friendly and kept everything well organized!', author: 'Roel V.' },
                        { text: 'Fantastic! Everything was perfectly arranged. The room was incredibly comfortable and the bed was wonderful. The breakfast was delicious.', author: 'Pim v.W.' },
                        { text: 'Highly recommended! Everything has been thought of. The breakfast: warm rolls, fresh juice, and yogurt made by Henk. A 5-star hotel can\'t compare.', author: 'Debbie d.L.' },
                    ],
                },
                {
                    name: 'Stadsslaperij B&B',
                    description: 'Persoonlijke B&B gerund door gastheer Michel. Sfeervolle kamers met oog voor detail, heerlijk ontbijt en een terras. Op loopafstand van het centrum.',
                    address: 'Fatimastraat 91, 5021 AM Tilburg',
                    coords: [51.5507, 5.0998],
                    link: 'https://www.destadsslaperij.nl',
                    tags: ['B&B', 'persoonlijk', 'ontbijt'],
                    image: 'https://impro.usercontent.one/appid/oneComWsb/domain/destadsslaperij.nl/media/destadsslaperij.nl/onewebmedia/20201010_112026___serialized1.jpg?etag=%2255ec95-61d835b8%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=1600,720&quality=85',
                    priceLevel: 2,
                    rating: 4.9,
                    openingHours: '24/7 bereikbaar',
                    reviews: [
                        { text: 'We stayed now a second time at this little gem and absolutely loved it. The rooms are lovely decorated and really well thought of. The breakfast is delicious!', author: 'Sabrina P.' },
                        { text: 'Everything about the bnb was perfect. Breakfast was superb. All the little touches and attention to detail were exemplary.', author: 'Valerie R.' },
                        { text: 'Spacious rooms, very comfortable bedding, healthy breakfast. But the real plus is Michel\'s kindness and level of attention.', author: 'Romain A.' },
                    ],
                },
            ],
        },
        {
            type: 'cocktail',
            icon: 'martini',
            label: 'Cocktailbars',
            color: '#D4A3A3',
            places: [
                {
                    name: 'Goesting',
                    description: 'Gezellige bar aan de Heuvelstraat met een warm interieur, heerlijke borrelplanken en een verborgen tuin op het terras. Perfecte plek voor een zomerse avond.',
                    address: 'Heuvelstraat 139a, 5038 AD Tilburg',
                    coords: [51.5553, 5.0825],
                    link: 'https://www.goestingtilburg.nl/',
                    tags: ['borrel', 'tuin', 'gezellig'],
                    image: 'https://www.goestingtilburg.nl/img/250408_GOESTING_HR_022.jpg',
                    priceLevel: 2,
                    rating: 5.0,
                    openingHours: 'Wo: 16:00 - 00:00, Do: 16:00 - 01:00, Vr - Zo: 14:00 - 01:00',
                    isWildcard: true,
                    reviews: [
                        { text: 'Great place for a drink. Delicious drinks and the snacks are also top notch.', author: 'Tom B.' },
                        { text: 'A lively atmosphere, delicious snacks including delicious cheeses, and friendly staff. Highly recommended!', author: 'Jolien B.' },
                        { text: 'Summer evenings or autumnal afternoons are perfect here. The warm atmosphere is created by both the beautiful interior and the friendly service!', author: 'Kaz D.' },
                    ],
                },
                {
                    name: 'Strøming Rooftopbar',
                    description: 'Rooftopbar met spectaculair uitzicht over de Spoorzone en Tilburg. Bijzondere cocktails in een unieke setting hoog boven de stad.',
                    address: 'Spoorlaan 21D, 5038 CB Tilburg',
                    coords: [51.5599, 5.0889],
                    link: 'https://www.stromingtilburg.nl/',
                    tags: ['rooftop', 'uitzicht', 'Spoorzone'],
                    image: 'https://www.stromingtilburg.nl/wp-content/uploads/2025/06/20250411-Stroming-Tilbrug-Rooftop-LR-19.jpg',
                    priceLevel: 2,
                    rating: 4.4,
                    openingHours: 'Ma - Do: 12:00 - 00:00, Vr - Za: 12:00 - 01:00, Zo: 12:00 - 00:00',
                    reviews: [
                        { text: 'Super cozy inside dining experience with shared meals, also this midnight blossom cocktail is probably the best cocktail I\'ve ever had.', author: 'Tim R.' },
                        { text: 'The place is beautifully decorated. The menu offers a great selection, with cocktails that are genuinely well-crafted.', author: 'Guilherme G.' },
                        { text: 'The food was good, as always. A queer-friendly space, which only adds to its appeal.', author: 'Uljana A.' },
                    ],
                },
                {
                    name: 'NØIR Borrel & Bites',
                    description: 'Sfeervol café met excellente cocktails en borrelplanken. In de zomer een prachtige verborgen tuin. Intiem en warm.',
                    address: 'Nieuwlandstraat 51, 5038 SM Tilburg',
                    coords: [51.5555, 5.0828],
                    link: 'https://www.noir.nl/',
                    tags: ['borrel', 'tuin', 'intiem'],
                    image: 'https://www.noir.nl/upload/items/2000/141/etalage-bar.png',
                    priceLevel: 2,
                    rating: 4.7,
                    openingHours: 'Wo - Za: 14:00 - 00:00, Zo: 14:00 - 22:00',
                    reviews: [
                        { text: 'The best bar in Tilburg. High quality snacks, great cocktails, lovely workers and nice atmosphere.', author: 'Clara M.' },
                        { text: 'Fantastic designed bar, amazing lunch.', author: 'patheesen' },
                        { text: 'Noir Borrel & Bites has become our ultimate hangout spot, a place where every visit feels like a cherished reunion.', author: 'Globe Voyage' },
                    ],
                },
                {
                    name: 'Gin Fizz',
                    description: 'Gezellige cocktailbar gespecialiseerd in premium gin-cocktails. Warme sfeer met intiem interieur en deskundige bartenders.',
                    address: 'Oranjestraat 6, 5038 WD Tilburg',
                    coords: [51.5552, 5.0892],
                    link: 'http://www.gin-fizz.nl/',
                    tags: ['gin', 'premium', 'nachtleven'],
                    image: 'https://www.gin-fizz.nl/wp-content/uploads/2023/02/SfeerfotoGinFizz_Fever-Tree.png',
                    priceLevel: 2,
                    rating: 4.5,
                    openingHours: 'Do: 22:00 - 03:00, Vr - Za: 21:00 - 04:00',
                    reviews: [
                        { text: 'Nice cocktails and music.', author: 'Aimee C.' },
                        { text: 'Really cozy, fun and great Gin cocktails served by a well informed, nice staff.', author: 'Artëm D.' },
                        { text: 'Great relaxing place, nice staff.', author: 'Vic V.' },
                    ],
                },
            ],
        },
        {
            type: 'restaurant',
            icon: 'utensils',
            label: 'Restaurants',
            color: '#D19C5B',
            places: [
                {
                    name: 'Gist',
                    description: 'Een van de beste restaurants van Tilburg. Seizoensgebonden deelgerechten met lokale ingrediënten. Groenten in de hoofdrol. Klein en snel volgeboekt!',
                    address: 'Langestraat 65, 5038 SC Tilburg',
                    coords: [51.5555, 5.0841],
                    link: 'http://www.gisttilburg.nl/',
                    tags: ['fine dining', 'lokaal', 'seizoensgebonden'],
                    image: 'https://gisttilburg.nl/wp-content/uploads/2024/03/Header-GIST-Tilburg-1-scaled.jpg',
                    priceLevel: 3,
                    rating: 4.9,
                    openingHours: 'Ma - Vr: 17:00 - 22:00, Za - Zo: 12:00 - 15:00 & 17:00 - 22:00',
                    reviews: [
                        { text: 'Oh my God! Just are serving the best possible cabbage, maybe the best in the world. The sauce to it was magical.', author: 'Mindaugas x' },
                        { text: 'Great modern cuisine, dishes to share, amazing quality yet not too fancy. Best in class chicken or North Sea fish.', author: 'Roan v.d.K.' },
                        { text: 'It was truly the best decision to choose GIST for my PhD defense dinner! All of my guests thoroughly enjoyed the delicious food.', author: 'Zihao L.' },
                    ],
                },
                {
                    name: 'Sarban',
                    description: 'Afghaans restaurant, een begrip in Tilburg. Probeer de Afghaanse proeverij voor een compleet smaakavontuur. Op loopafstand van het station.',
                    address: 'Besterdring 2, 5014 HL Tilburg',
                    coords: [51.5671, 5.0887],
                    link: 'http://www.sarban.nl/',
                    tags: ['Afghaans', 'proeverij', 'populair'],
                    image: 'https://sarban.nl/wp-content/uploads/2019/09/mantoe.jpg',
                    priceLevel: 2,
                    rating: 4.8,
                    openingHours: 'Di - Zo: 17:00 - 22:00',
                    reviews: [
                        { text: 'A truly cozy, family-run spot. The food was excellent — from tender lamb and flavorful veal to the delicious stuffed meat dumplings.', author: 'Rolitta S.' },
                        { text: 'Everything tastes homemade but also very professional! A great experience enjoying delicious Afghan dishes.', author: 'Shima' },
                        { text: 'We opted for the chef\'s recommended menu. We were not disappointed! The food was well presented and flavoursome.', author: 'Patty v.H.' },
                    ],
                },
                {
                    name: 'Pulcinos',
                    description: 'Italiaans-geïnspireerd restaurant aan de Piushaven met open keuken en loungehoek. Dagverse lokale ingrediënten, huisgemaakte limoncello en fantastische cocktails.',
                    address: 'Piushaven 20B, 5017 AN Tilburg',
                    coords: [51.5527, 5.0949],
                    link: 'http://www.pulcinos.nl/',
                    tags: ['Italiaans', 'Piushaven', 'open keuken'],
                    priceLevel: 2,
                    rating: 4.8,
                    openingHours: 'Ma, Wo - Do: 17:00 - 23:00, Vr - Za: 12:00 - 00:00, Zo: 12:00 - 23:00',
                    reviews: [
                        { text: 'Amazing place for dinner! The restaurant was cozy and a great vibe. The food was really fresh and tasty.', author: 'Joi C.' },
                        { text: 'This is literally the only place I go to. I don\'t know what is better — the food, the atmosphere or the cocktails. Best food in town.', author: 'Mikaela I.' },
                        { text: 'Amazing food and atmosphere! Everything we ordered tasted like heaven! The chef has a talent for seafood dishes!', author: 'Bashayar A.' },
                    ],
                },
                {
                    name: 'Nomadas',
                    description: 'Verborgen parel in een woonwijk. Chefs combineren invloeden van Lanzarote, Ecuador en Madrid. Intiem tasting menu met verrassende smaken.',
                    address: 'Academielaan 73, 5037 EV Tilburg',
                    coords: [51.5577, 5.0557],
                    link: 'https://nomadas-gastrobar.nl/',
                    tags: ['tasting menu', 'verborgen', 'internationaal'],
                    image: 'https://nomadas-gastrobar.nl/wp-content/uploads/2024/01/Nomadas-Tafels-op-een-rij.jpg',
                    priceLevel: 3,
                    rating: 4.8,
                    openingHours: 'Wo - Vr: 17:30 - 23:30, Za - Zo: 17:30 - 00:00',
                    reviews: [
                        { text: 'Everything was delicious and presented with such creative care! The atmosphere is incredible, as if you were on vacation!', author: 'Minerva I.' },
                        { text: 'Highly recommended. It was a feast on my tongue. The portion and the price are very reasonable.', author: 'Skye Y.' },
                        { text: 'The Tamarindo Old Fashion was liquid candy. Finally a restaurant that spices their food well!', author: 'jennifer s.' },
                    ],
                },
            ],
        },
        {
            type: 'culture',
            icon: 'ticket',
            label: 'Cultuur',
            color: '#8BAA99',
            places: [
                {
                    name: 'De Pont Museum',
                    description: 'Museum voor hedendaagse kunst in een voormalige wolspinnerij. Het gebouw zelf — met kenmerkend zaagtanddak — was inspiratie voor Tate Modern in Londen.',
                    address: 'Wilhelminapark 1, 5041 EA Tilburg',
                    coords: [51.5673, 5.0742],
                    link: 'http://www.depont.nl/',
                    tags: ['hedendaagse kunst', 'industrieel', 'architectuur'],
                    priceLevel: 2,
                    rating: 4.3,
                    openingHours: 'Di - Vr: 11:00 - 17:00, Do: 11:00 - 20:00, Za - Zo: 11:00 - 17:00',
                    reviews: [
                        { text: 'Fantastic / great building / fabulous exhibition with live persons very inspiring.', author: 'Wim d.R.' },
                        { text: 'For those who enjoy contemporary art, it is a great visit. Good curation and assembly. The space is an invitation to reflection.', author: 'Eduardo M.' },
                        { text: 'On my regular visits to The Netherlands this is always an essential visit. The vast space, a former factory, so there\'s plenty of space to enjoy the works.', author: 'Robin R.' },
                    ],
                },
                {
                    name: 'TextielMuseum',
                    description: 'Ontdek alles over textiel in een prachtig industrieel gebouw. Werkende weefgetouwen, hedendaagse kunsttentoonstellingen en het TextielLab waar kunstenaars produceren.',
                    address: 'Goirkestraat 96, 5046 GN Tilburg',
                    coords: [51.5709, 5.0795],
                    link: 'http://www.textielmuseum.nl/',
                    tags: ['textiel', 'industrieel erfgoed', 'interactief'],
                    image: 'https://textielm.ams3.cdn.digitaloceanspaces.com/content_pages_images/Photo-Patty van den Elshout i.o.v. TextielMuseum-2024-053-002.jpg',
                    priceLevel: 2,
                    rating: 4.4,
                    openingHours: 'Di - Vr: 10:00 - 17:00, Za - Zo: 12:00 - 17:00',
                    reviews: [
                        { text: 'A museum that\'s both educational and enjoyable for the whole family. You need at least 2 hours. Definitely worth the price.', author: 'Serkan K.' },
                        { text: 'Fantastic museum housed in a historic building. The exhibits are informative and interactive. Everything on display is absolutely gorgeous.', author: 'Yusuf K.' },
                        { text: 'I really enjoyed it. I was fascinated by how the huge loom machine works. Really interesting museum for everyone.', author: 'JU C.' },
                    ],
                },
                {
                    name: 'Poppodium 013',
                    description: 'Legendarisch poppodium voor live muziek en dancenights. Een van de beste poppodia van Nederland. Geweldige akoestiek en sfeer.',
                    address: 'Veemarktstraat 44, 5017 HS Tilburg',
                    coords: [51.5579, 5.0928],
                    link: 'http://www.013.nl/',
                    tags: ['live muziek', 'poppodium', 'dans'],
                    priceLevel: 2,
                    rating: 4.6,
                    openingHours: 'Kassa: Ma - Vr 13:00 - 17:00, avondprogramma varieert',
                    reviews: [
                        { text: 'The sound quality was excellent, and the view was amazing from every spot in the venue. Very reasonably priced!', author: 'dots' },
                        { text: 'Great stage, not too big but still enough for a nice crowd. Excellent location and great bands.', author: 'Rob v.P.' },
                        { text: 'Great acoustics — not too big but not too small. Love the stadium-style risers in the back, perfect for shorter people.', author: 'mersaydees m.' },
                    ],
                },
                {
                    name: 'Cinecitta',
                    description: 'Filmtheater met arthouse films, bijzondere vertoningen en een gezellige bar. De filmervaring die je zoekt, geen standaard bioscoop.',
                    address: 'Willem II Straat 29, 5038 BA Tilburg',
                    coords: [51.5584, 5.0862],
                    link: 'http://www.cinecitta.nl/',
                    tags: ['arthouse', 'filmtheater', 'bar'],
                    image: 'https://cinecittatilburg.nl/wp-content/uploads/2022/08/20201130_Cinecitta2_Fotografie-Jules-van-Iperen_026-2.jpg',
                    priceLevel: 2,
                    rating: 4.5,
                    openingHours: 'Dagelijks: 10:00 - 22:30',
                    reviews: [
                        { text: 'The perfect place to relax and enjoy a nice meal and movie. The restaurant is in a beautiful room with high ceilings and art.', author: 'Ian M.' },
                        { text: 'An amazing gem in the heart of Tilburg! Very clean, very comfortable chairs, nice selection of international movies.', author: 'Lora B.' },
                        { text: 'Best personal and service. I personally highly recommend.', author: 'Jose Luis L.' },
                    ],
                },
            ],
        },
    ],
};
